### ISSUE TITLE
Feedback on node design

### ISSUE THREAD

**Issue by alexisrolland** [spacepxl/ComfyUI-Depth-Pro#4]
Hello there,
Great work packaging this so quickly!

If I may just share a feedback in terms of design, I think the nodes `MetricDepthToRelative` and `MetricDepthToInverse` could be directly integrated into `DepthPro`. 99% of the people who will run this model will want to get an image as input rather than depth measurements, so I think this could be default behavior. It would simplify the user experience, rather than having to add these extra nodes.

Cheers

**Comment by spacepxl** [comment]
The reason I separated it out is to avoid recomputing the depth estimates just to adjust the metric->relative conversion. There's a high chance of needing to change the per-image normalization (depending on which option flickers less) or gamma, especially for video. It's the same reason why the model loading is separated, so you don't need to keep reloading it. The approach of combining model loading + processing + postprocessing into a single node like in controlnet_aux is fine for small models, but it's wasteful for larger models like this. If you want to use it like a single node though, you can always select multiple nodes and convert them into a group node.

Besides, I don't agree with your 99% claim. The metric depth capabilities of this are good enough that downstream uses like 3d projection will be more common than with previous relative depth models like Marigold and DepthAnythingV2.

**Comment by alexisrolland** [comment]
Good point on the computational optimization.
