### ISSUE TITLE
Feeding the focal length

### ISSUE THREAD

**Issue by hbardak** [spacepxl/ComfyUI-Depth-Pro#5]
Hi ! 

Thank you so much for implementing this node 

By reading the paper and code, I could see that you can feed the focal length in pixel rather than estimating it. I feel that may improve the result especially for video. 
It is a guess but would it be possible to expose the parameter ?

**Comment by spacepxl** [comment]
yes, added with https://github.com/spacepxl/ComfyUI-Depth-Pro/commit/2164e20feebf49fbb92164bff18cf3951b8d6838 along with helper nodes to convert focal length between px and mm

**Comment by hbardak** [comment]
Awesome thank you !
